from __future__ import annotations

import re
import unicodedata

from .schemas import AssembledChapter, AssembledSection, AssemblyFrontMatter, LatexManuscript


COMMON_TEXT_REPLACEMENTS = {
    "\u00a0": " ",
    "\u2010": "-",
    "\u2011": "-",
    "\u2012": "-",
    "\u2013": "--",
    "\u2014": "---",
    "\u2018": "'",
    "\u2019": "'",
    "\u201c": "``",
    "\u201d": "''",
    "\u2026": "...",
    "\u2212": "-",
    "\u221a": "sqrt",
    # Box-drawing characters used in directory trees and ASCII art
    "\u2500": "-",   # ─  BOX DRAWINGS LIGHT HORIZONTAL
    "\u2501": "=",   # ━  BOX DRAWINGS HEAVY HORIZONTAL
    "\u2502": "|",   # │  BOX DRAWINGS LIGHT VERTICAL
    "\u2503": "|",   # ┃  BOX DRAWINGS HEAVY VERTICAL
    "\u250c": "+",   # ┌  BOX DRAWINGS LIGHT DOWN AND RIGHT
    "\u2510": "+",   # ┐  BOX DRAWINGS LIGHT DOWN AND LEFT
    "\u2514": "+",   # └  BOX DRAWINGS LIGHT UP AND RIGHT
    "\u2518": "+",   # ┘  BOX DRAWINGS LIGHT UP AND LEFT
    "\u251c": "+",   # ├  BOX DRAWINGS LIGHT VERTICAL AND RIGHT
    "\u2524": "+",   # ┤  BOX DRAWINGS LIGHT VERTICAL AND LEFT
    "\u252c": "+",   # ┬  BOX DRAWINGS LIGHT DOWN AND HORIZONTAL
    "\u2534": "+",   # ┴  BOX DRAWINGS LIGHT UP AND HORIZONTAL
    "\u253c": "+",   # ┼  BOX DRAWINGS LIGHT VERTICAL AND HORIZONTAL
    "\u2550": "=",   # ═  BOX DRAWINGS DOUBLE HORIZONTAL
    "\u2551": "|",   # ║  BOX DRAWINGS DOUBLE VERTICAL
    "\u255a": "+",   # ╚  BOX DRAWINGS DOUBLE UP AND RIGHT
    "\u2560": "+",   # ╠  BOX DRAWINGS DOUBLE VERTICAL AND RIGHT
    "\u2566": "+",   # ╦  BOX DRAWINGS DOUBLE DOWN AND HORIZONTAL
    "\u256c": "+",   # ╬  BOX DRAWINGS DOUBLE VERTICAL AND HORIZONTAL
    # Arrows and other symbols commonly generated by LLMs
    "\u2192": "->",  # →
    "\u2190": "<-",  # ←
    "\u2194": "<->", # ↔
    "\u21d2": "=>",  # ⇒
    "\u21d4": "<=>", # ⇔
    "\u2022": "*",   # •  BULLET
    "\u25cf": "*",   # ●  BLACK CIRCLE
    "\u25cb": "o",   # ○  WHITE CIRCLE
    "\u25a0": "[]",  # ■  BLACK SQUARE
    "\u25a1": "[]",  # □  WHITE SQUARE
    "\u2713": "OK",  # ✓  CHECK MARK
    "\u2717": "X",   # ✗  BALLOT X
    "\u00b7": ".",   # ·  MIDDLE DOT
    "\u00d7": "x",   # ×  MULTIPLICATION SIGN
    "\u00f7": "/",   # ÷  DIVISION SIGN
    "\u00b1": "+/-", # ±  PLUS-MINUS SIGN
    "\u2248": "~=",  # ≈  ALMOST EQUAL TO
    "\u2260": "!=",  # ≠  NOT EQUAL TO
    "\u2264": "<=",  # ≤  LESS-THAN OR EQUAL TO
    "\u2265": ">=",  # ≥  GREATER-THAN OR EQUAL TO
    "\u00ae": "(R)", # ®  REGISTERED SIGN
    "\u2122": "(TM)",# ™  TRADE MARK SIGN
    "\u00a9": "(C)", # ©  COPYRIGHT SIGN
}

PRIVATE_SOURCE_URL_PATTERN = re.compile(
    r"(?:file://|/app/\.cache|/Users/)[^\s\]\)>,]*",
    flags=re.IGNORECASE,
)
HTML_MATH_TAG_PATTERN = re.compile(
    r"(?P<base>[A-Za-z0-9]+)?<(?P<tag>sub|sup)>(?P<body>[^<>]{1,64})</(?P=tag)>",
    flags=re.IGNORECASE,
)
SELF_CORRECTION_PATTERN = re.compile(
    r"\b(?:there appears to be an error|there was an error|let'?s recalculate|previous calculation was wrong)\b",
    flags=re.IGNORECASE,
)


def render_latex_manuscript(
    *,
    front_matter: AssemblyFrontMatter,
    chapters: list[AssembledChapter],
) -> LatexManuscript:
    parts = [
        _render_preamble(),
        "\\begin{document}",
    ]

    if front_matter.include_title_page:
        parts.append(_render_title_page(front_matter))

    parts.append("\\frontmatter")

    if front_matter.include_toc:
        parts.append("\\tableofcontents")

    parts.append("\\mainmatter")

    for chapter in chapters:
        parts.append(_render_chapter(chapter))

    parts.append("\\end{document}")

    return LatexManuscript(
        content="\n\n".join(part for part in parts if part.strip()),
    )


def _render_preamble() -> str:
    return "\n".join(
        [
            "\\documentclass[11pt,oneside,openany]{scrbook}",
            "\\usepackage{iftex}",
            "\\ifPDFTeX",
            "\\usepackage[T1]{fontenc}",
            "\\usepackage[utf8]{inputenc}",
            "\\usepackage{lmodern}",
            "\\else",
            "\\usepackage{fontspec}",
            "\\fi",
            "\\usepackage{microtype}",
            "\\usepackage[a4paper,margin=1in]{geometry}",
            "\\usepackage{hyperref}",
            "\\usepackage{url}",
            "\\usepackage{xurl}",
            "\\usepackage{bookmark}",
            "\\usepackage{enumitem}",
            "\\usepackage{listings}",
            "\\usepackage{xcolor}",
            "\\usepackage{graphicx}",
            "\\usepackage{float}",
            "\\usepackage{tikz}",
            "\\usetikzlibrary{arrows.meta,positioning,shapes.geometric,backgrounds,fit}",
            "\\usepackage{pgfplots}",
            "\\pgfplotsset{compat=1.18}",
            "\\usepackage{tcolorbox}",
            "\\tcbuselibrary{listings,skins}",
            "",
            "% NCERT-inspired learning palette",
            "\\definecolor{brandblue}{RGB}{25,83,157}",
            "\\definecolor{brandteal}{RGB}{0,122,128}",
            "\\definecolor{brandgreen}{RGB}{46,125,50}",
            "\\definecolor{brandorange}{RGB}{239,124,0}",
            "\\definecolor{softblue}{RGB}{232,242,255}",
            "\\definecolor{softgreen}{RGB}{235,248,236}",
            "\\definecolor{softyellow}{RGB}{255,248,225}",
            "\\definecolor{softred}{RGB}{255,235,238}",
            "\\addtokomafont{chapter}{\\color{brandblue}}",
            "\\addtokomafont{section}{\\color{brandteal}}",
            "\\addtokomafont{subsection}{\\color{brandorange}}",
            "\\hypersetup{colorlinks=true,linkcolor=brandblue,urlcolor=brandteal,citecolor=brandgreen}",
            "\\hypersetup{hypertexnames=false}",
            "\\Urlmuskip=0mu plus 1mu",
            "\\emergencystretch=3em",
            "",
            "% Code listing style",
            "\\definecolor{codebg}{RGB}{248,250,252}",
            "\\definecolor{codeframe}{RGB}{156,178,204}",
            "\\definecolor{codecomment}{RGB}{106,153,85}",
            "\\definecolor{codestring}{RGB}{163,21,21}",
            "\\definecolor{codekeyword}{RGB}{25,83,157}",
            "",
            "\\lstdefinestyle{bookcode}{",
            "  backgroundcolor=\\color{codebg},",
            "  frame=single,",
            "  rulecolor=\\color{codeframe},",
            "  basicstyle=\\ttfamily\\small,",
            "  keywordstyle=\\color{codekeyword}\\bfseries,",
            "  commentstyle=\\color{codecomment}\\itshape,",
            "  stringstyle=\\color{codestring},",
            "  showstringspaces=false,",
            "  breaklines=true,",
            "  breakatwhitespace=true,",
            "  tabsize=4,",
            "  numbers=left,",
            "  numberstyle=\\tiny\\color{gray},",
            "  numbersep=8pt,",
            "  xleftmargin=2em,",
            "  framexleftmargin=1.5em,",
            "  captionpos=b,",
            "}",
            "\\lstset{style=bookcode}",
            "",
            "% Diagram placeholder box",
            "\\newtcolorbox{diagramplaceholder}[2][]{",
            "  colback=softblue,",
            "  colframe=brandblue,",
            "  title={#2},",
            "  fonttitle=\\bfseries,",
            "  #1",
            "}",
            "\\newtcolorbox{conceptbox}[1][]{",
            "  colback=softyellow,",
            "  colframe=brandorange,",
            "  title={Key Idea},",
            "  fonttitle=\\bfseries,",
            "  #1",
            "}",
            "\\newtcolorbox{checkpointbox}[1][]{",
            "  colback=softblue,",
            "  colframe=brandteal,",
            "  title={Checkpoint},",
            "  fonttitle=\\bfseries,",
            "  #1",
            "}",
            "",
            "% Exercise box",
            "\\newtcolorbox{exercisebox}[1][]{",
            "  colback=softgreen,",
            "  colframe=brandgreen,",
            "  title={Try It Yourself},",
            "  fonttitle=\\bfseries,",
            "  #1",
            "}",
            "",
            "% Common mistakes box",
            "\\newtcolorbox{gotchabox}[1][]{",
            "  colback=softred,",
            "  colframe=red!65!black,",
            "  title={Common Mistakes},",
            "  fonttitle=\\bfseries,",
            "  #1",
            "}",
            "",
            "\\KOMAoptions{parskip=half}",
            "\\setlist[itemize]{leftmargin=2em}",
            "\\setlist[enumerate]{leftmargin=2em}",
        ]
    )


def _render_title_page(front_matter: AssemblyFrontMatter) -> str:
    title = _escape_latex(front_matter.title)
    audience = _escape_latex(front_matter.audience)
    tone = _escape_latex(front_matter.tone)
    depth = _escape_latex(front_matter.depth)

    return "\n".join(
        [
            "\\begin{titlepage}",
            "\\centering",
            "\\vspace*{0.18\\textheight}",
            "{\\Huge\\bfseries " + title + "\\par}",
            "\\vspace{1.5cm}",
            "{\\Large Generated Book Manuscript\\par}",
            "\\vspace{1.2cm}",
            "{\\large Audience: " + audience + "\\par}",
            "\\vspace{0.3cm}",
            "{\\large Tone: " + tone + "\\par}",
            "\\vspace{0.3cm}",
            "{\\large Depth: " + depth + "\\par}",
            "\\vfill",
            "\\end{titlepage}",
        ]
    )


def _render_chapter(chapter: AssembledChapter) -> str:
    parts = [
        _render_comment("chapter_id", chapter.chapter_id),
        _render_comment("chapter_goal", chapter.chapter_goal),
        "\\chapter{" + _escape_latex(chapter.chapter_title) + "}",
    ]

    for section in chapter.sections:
        parts.append(_render_section(section))

    return "\n\n".join(part for part in parts if part.strip())


def _render_section(section: AssembledSection) -> str:
    parts = [
        _render_comment("section_id", section.section_id),
        _render_comment("review_status", section.review_status.value),
        _render_comment(
            "reviewer_warnings",
            ",".join(w.value for w in section.reviewer_warnings),
        ),
        _render_comment("citations_used", ",".join(section.citations_used)),
        "\\section{" + _escape_latex(section.section_title) + "}",
        "\\label{" + section.latex_label + "}",
        _render_content_blocks(section.content),
    ]

    return "\n".join(part for part in parts if part)


def _render_content_blocks(text: str) -> str:
    prepared = _prepare_text(text)
    segments = _split_code_and_text(prepared)
    rendered_blocks: list[str] = []

    for segment_type, segment_content in segments:
        if segment_type == "code":
            rendered_blocks.append(segment_content)
        elif segment_type == "diagram":
            rendered_blocks.append(segment_content)
        else:
            blocks = _split_blocks(segment_content)
            index = 0
            while index < len(blocks):
                block = blocks[index]
                leading_heading, remaining_block = _split_leading_heading(block)
                if leading_heading and remaining_block:
                    if _is_callout_heading(leading_heading):
                        rendered_blocks.append(
                            _render_callout_block(leading_heading, remaining_block)
                        )
                    else:
                        rendered_blocks.append(_render_heading(leading_heading))
                        rendered_blocks.append(_render_plain_block(remaining_block))
                    index += 1
                    continue

                heading = _extract_standalone_heading(block)

                if heading and _is_callout_heading(heading) and index + 1 < len(blocks):
                    rendered_blocks.append(
                        _render_callout_block(heading, blocks[index + 1])
                    )
                    index += 2
                    continue

                if heading:
                    rendered_blocks.append(_render_heading(heading))
                elif _is_bullet_list(block):
                    rendered_blocks.append(_render_itemize(block))
                elif _is_enumerated_list(block):
                    rendered_blocks.append(_render_enumerate(block))
                else:
                    rendered_blocks.append(_render_paragraph(block))
                index += 1

    return "\n\n".join(block for block in rendered_blocks if block.strip())


def _split_code_and_text(text: str) -> list[tuple[str, str]]:
    """Split text into segments: ('text', content), ('code', latex), ('diagram', latex)."""
    segments: list[tuple[str, str]] = []
    lines = text.split("\n")
    i = 0
    current_text_lines: list[str] = []

    while i < len(lines):
        line = lines[i]

        # Check for fenced code block: ```language
        if line.strip().startswith("```") and not line.strip() == "```":
            # Flush accumulated text
            if current_text_lines:
                segments.append(("text", "\n".join(current_text_lines)))
                current_text_lines = []

            lang_hint = line.strip().lstrip("`").strip().lower()
            code_lines: list[str] = []
            i += 1
            while i < len(lines) and not lines[i].strip().startswith("```"):
                code_lines.append(lines[i])
                i += 1
            if i < len(lines):
                i += 1  # skip closing ```

            code_content = "\n".join(code_lines)
            latex_lang = _map_language_to_lstlisting(lang_hint)
            latex_code = (
                f"\\begin{{lstlisting}}[language={latex_lang}]\n"
                f"{code_content}\n"
                f"\\end{{lstlisting}}"
            )
            segments.append(("code", latex_code))
            continue

        # Check for DIAGRAM: hint
        if line.strip().startswith("DIAGRAM:"):
            if current_text_lines:
                segments.append(("text", "\n".join(current_text_lines)))
                current_text_lines = []

            diagram_hint = line.strip()[len("DIAGRAM:"):].strip()
            desc_lines: list[str] = []
            i += 1
            while i < len(lines) and lines[i].strip() and not lines[i].strip().startswith("DIAGRAM:") and not lines[i].strip().startswith("```"):
                desc_lines.append(lines[i].strip())
                i += 1

            latex_diagram = _render_diagram_hint(
                diagram_hint=diagram_hint,
                desc_lines=desc_lines,
            )
            segments.append(("diagram", latex_diagram))
            continue

        current_text_lines.append(line)
        i += 1

    if current_text_lines:
        segments.append(("text", "\n".join(current_text_lines)))

    return segments


def _render_diagram_hint(*, diagram_hint: str, desc_lines: list[str]) -> str:
    diagram_type, title = _parse_diagram_title(diagram_hint)
    description_lines = [
        line
        for line in desc_lines
        if not line.lower().startswith("elements:")
    ]
    elements = _parse_diagram_elements(desc_lines)
    description = " ".join(description_lines).strip() or title or "Diagram"

    safe_title = _escape_latex(title or "Diagram")
    safe_desc = _escape_latex_with_urls(description)
    tikz = _render_tikz_diagram(elements, diagram_type=diagram_type)

    return "\n".join(
        [
            "\\begin{figure}[H]",
            "\\centering",
            f"\\begin{{diagramplaceholder}}{{{safe_title}}}",
            tikz,
            "\\vspace{0.35em}",
            safe_desc,
            "\\end{diagramplaceholder}",
            f"\\caption{{{safe_title}}}",
            "\\end{figure}",
        ]
    )


def _parse_diagram_title(diagram_hint: str) -> tuple[str, str]:
    cleaned = diagram_hint.strip()
    match = re.match(r"^\[([^\]]+)\]\s*-\s*(.+)$", cleaned)
    if match:
        return match.group(1).strip(), match.group(2).strip()

    match = re.match(r"^([^:-]+)\s*[-:]\s*(.+)$", cleaned)
    if match:
        return match.group(1).strip(), match.group(2).strip()

    return "flowchart", cleaned or "Diagram"


def _parse_diagram_elements(desc_lines: list[str]) -> list[str]:
    for line in desc_lines:
        if not line.lower().startswith("elements:"):
            continue
        raw = line.split(":", 1)[1]
        elements = [
            item.strip(" .;")
            for item in raw.split(",")
            if item.strip(" .;")
        ]
        if elements:
            return elements[:9]
    return []


def _render_tikz_diagram(elements: list[str], *, diagram_type: str) -> str:
    if not elements:
        elements = ["Idea", "Example", "Implementation", "Result"]

    style = (
        "draw=brandblue, fill=white, rounded corners=4pt, "
        "align=center, text width=3.1cm, minimum height=1cm, font=\\small"
    )
    lines = [
        "\\begin{tikzpicture}[>=Stealth, node distance=0.8cm]",
    ]

    for index, element in enumerate(elements[:9]):
        row = index // 3
        col = index % 3
        x_pos = col * 4.0
        y_pos = -row * 1.6
        safe_element = _escape_latex(element)
        lines.append(
            f"\\node[{style}] (n{index}) at ({x_pos},{y_pos}) {{{safe_element}}};"
        )

    for index in range(min(len(elements[:9]) - 1, 8)):
        lines.append(f"\\draw[->, thick, brandteal] (n{index}) -- (n{index + 1});")

    safe_type = _escape_latex(diagram_type or "flowchart")
    lines.extend(
        [
            "\\begin{scope}[on background layer]",
            "\\node[fill=softblue, rounded corners=6pt, fit=(n0) (n"
            + str(min(len(elements[:9]) - 1, 8))
            + "), inner sep=8pt] {};",
            "\\end{scope}",
            f"\\node[above=0.25cm of n0, text=brandblue, font=\\bfseries\\small] {{{safe_type}}};",
            "\\end{tikzpicture}",
        ]
    )
    return "\n".join(lines)


def _map_language_to_lstlisting(lang_hint: str) -> str:
    """Map a fenced code block language hint to lstlisting language name."""
    mapping = {
        "python": "Python",
        "py": "Python",
        "bash": "bash",
        "sh": "bash",
        "shell": "bash",
        "javascript": "JavaScript",
        "js": "JavaScript",
        "json": "Python",
        "sql": "SQL",
        "text": "",
        "output": "",
        "": "",
    }
    return mapping.get(lang_hint, "")


def _render_itemize(lines: list[str]) -> str:
    items = ["\\item " + _escape_latex_with_urls(_strip_list_marker(line)) for line in lines]
    return "\n".join(["\\begin{itemize}", *items, "\\end{itemize}"])


def _render_enumerate(lines: list[str]) -> str:
    items = ["\\item " + _escape_latex_with_urls(_strip_enum_marker(line)) for line in lines]
    return "\n".join(["\\begin{enumerate}", *items, "\\end{enumerate}"])


def _render_paragraph(lines: list[str]) -> str:
    paragraph = " ".join(line.strip() for line in lines if line.strip())
    return _escape_latex_with_urls(paragraph)


def _render_plain_block(block: list[str]) -> str:
    if _is_bullet_list(block):
        return _render_itemize(block)
    if _is_enumerated_list(block):
        return _render_enumerate(block)
    return _render_paragraph(block)


def _render_heading(heading: str) -> str:
    return "\\subsection*{" + _escape_latex(heading) + "}"


def _render_callout_block(heading: str, block: list[str]) -> str:
    normalized = heading.lower()
    content = (
        _render_itemize(block)
        if _is_bullet_list(block)
        else _render_enumerate(block)
        if _is_enumerated_list(block)
        else _render_paragraph(block)
    )

    if "mistake" in normalized or "gotcha" in normalized:
        return "\n".join(["\\begin{gotchabox}", content, "\\end{gotchabox}"])
    if "exercise" in normalized or "try" in normalized or "activity" in normalized:
        return "\n".join(["\\begin{exercisebox}", content, "\\end{exercisebox}"])
    if "checkpoint" in normalized:
        return "\n".join(["\\begin{checkpointbox}", content, "\\end{checkpointbox}"])
    return "\n".join(["\\begin{conceptbox}", content, "\\end{conceptbox}"])


def _extract_standalone_heading(lines: list[str]) -> str | None:
    if len(lines) != 1:
        return None

    line = lines[0].strip()
    heading = _strip_heading_markup(line)
    if not heading:
        return None

    known_headings = {
        "concept",
        "intuition",
        "code example",
        "step-by-step implementation",
        "step by step implementation",
        "output",
        "expected result",
        "output / expected result",
        "common mistakes",
        "mini exercise",
        "try it yourself",
        "further reading",
        "activity",
        "checkpoint",
        "key idea",
    }
    normalized = heading.lower().strip(":")
    if normalized in known_headings:
        return heading.strip(":")

    if line.startswith(("#", "##", "###")) and len(heading) <= 80:
        return heading.strip(":")

    return None


def _split_leading_heading(lines: list[str]) -> tuple[str | None, list[str]]:
    if len(lines) < 2:
        return None, lines
    heading = _extract_standalone_heading([lines[0]])
    if heading:
        return heading, lines[1:]
    return None, lines


def _strip_heading_markup(line: str) -> str:
    stripped = line.strip()
    stripped = re.sub(r"^#{1,6}\s*", "", stripped)
    stripped = stripped.strip("*_ ")
    if stripped.startswith("**") and stripped.endswith("**"):
        stripped = stripped[2:-2]
    return stripped.strip()


def _is_callout_heading(heading: str) -> bool:
    normalized = heading.lower()
    return any(
        token in normalized
        for token in ("mistake", "gotcha", "exercise", "try", "activity", "checkpoint", "key idea")
    )


def _split_blocks(text: str) -> list[list[str]]:
    blocks: list[list[str]] = []
    current: list[str] = []

    for line in text.split("\n"):
        stripped = line.strip()
        if not stripped:
            if current:
                blocks.append(current)
                current = []
            continue

        current.append(stripped)

    if current:
        blocks.append(current)

    return blocks


def _is_bullet_list(lines: list[str]) -> bool:
    return bool(lines) and all(re.match(r"^([*-])\s+", line) for line in lines)


def _is_enumerated_list(lines: list[str]) -> bool:
    return bool(lines) and all(re.match(r"^\d+\.\s+", line) for line in lines)


def _strip_list_marker(line: str) -> str:
    return re.sub(r"^([*-])\s+", "", line, count=1)


def _strip_enum_marker(line: str) -> str:
    return re.sub(r"^\d+\.\s+", "", line, count=1)


def _prepare_text(text: str) -> str:
    normalized = _normalize_text_artifacts(text)
    normalized = normalized.replace("\r\n", "\n").replace("\r", "\n")
    normalized = _strip_private_source_blocks(normalized)
    normalized = re.sub(r"\n{3,}", "\n\n", normalized)
    return normalized.strip()


def _escape_latex_with_urls(text: str) -> str:
    """Escape *text* for LaTeX, honouring URLs and inline Markdown markup.

    Processing order (per non-URL segment):
    1. ``_escape_latex`` – handle special chars (\\, {, }, #, $, …)
    2. ``_apply_inline_markdown`` – convert **bold**, *italic*, ``code``
       spans that survived escaping back into LaTeX commands.
    """
    url_pattern = re.compile(r"(https?://[^\s\]\)>,]+)")
    parts: list[str] = []
    last_index = 0

    for match in url_pattern.finditer(text):
        if match.start() > last_index:
            parts.append(_render_inline_text_segment(text[last_index : match.start()]))
        url = match.group(1).rstrip(".,;")
        trailing = match.group(1)[len(url) :]
        parts.append("\\url{" + url.replace("\\", "/") + "}")
        if trailing:
            parts.append(_render_inline_text_segment(trailing))
        last_index = match.end()

    if last_index < len(text):
        parts.append(_render_inline_text_segment(text[last_index:]))

    return "".join(parts)


def _render_inline_text_segment(text: str) -> str:
    """Escape a non-URL prose segment while preserving safe inline math tags."""
    if not text:
        return ""

    rendered: list[str] = []
    last_index = 0

    for match in HTML_MATH_TAG_PATTERN.finditer(text):
        if match.start() > last_index:
            rendered.append(
                _apply_inline_markdown(_escape_latex(text[last_index : match.start()]))
            )

        base = match.group("base") or ""
        tag = match.group("tag").lower()
        body = _latex_math_body(match.group("body"))
        math_base = _latex_math_identifier(base)

        if tag == "sub":
            rendered.append(f"\\ensuremath{{{math_base}_{{{body}}}}}")
        else:
            rendered.append(f"\\ensuremath{{{math_base}^{{{body}}}}}")
        last_index = match.end()

    if last_index < len(text):
        rendered.append(_apply_inline_markdown(_escape_latex(text[last_index:])))

    return "".join(rendered)


def _latex_math_identifier(value: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9]", "", value.strip())
    if not cleaned:
        return "{}"
    if len(cleaned) == 1 and cleaned.isalpha():
        return cleaned
    return r"\mathrm{" + _latex_math_body(cleaned) + "}"


def _latex_math_body(value: str) -> str:
    normalized = _normalize_text_artifacts(value)
    replacements = {
        " ": r"\,",
        "_": r"\_",
        "%": r"\%",
        "#": r"\#",
        "&": r"\&",
        "{": r"\{",
        "}": r"\}",
        "\\": r"\backslash{}",
    }
    return "".join(replacements.get(char, char) for char in normalized if ord(char) <= 127)


def _apply_inline_markdown(escaped_text: str) -> str:
    """Convert Markdown inline spans inside already-LaTeX-escaped text.

    Handles, in order:
    * ``**bold**``   → ``\\textbf{bold}``
    * ``*italic*``   → ``\\textit{italic}``
    * `` `code` ``   → ``\\texttt{code}``

    The input must already have been run through ``_escape_latex`` so that
    special characters inside the spans are safe.  The surrounding markers
    (``**``, ``*``, back-ticks) are themselves just plain ASCII and are
    never escaped by ``_escape_latex``, so they can be matched and removed
    here without ambiguity.
    """
    # Bold: **...** (non-greedy, must not span newlines)
    text = re.sub(
        r"\*\*(.+?)\*\*",
        lambda m: r"\textbf{" + m.group(1) + "}",
        escaped_text,
    )
    # Italic: *...* (only single asterisks remaining after bold pass)
    text = re.sub(
        r"(?<!\*)\*([^*\n]+?)\*(?!\*)",
        lambda m: r"\textit{" + m.group(1) + "}",
        text,
    )
    # Inline code: `...`
    text = re.sub(
        r"`([^`\n]+?)`",
        lambda m: r"\texttt{" + m.group(1) + "}",
        text,
    )
    return text


def _escape_latex(text: str) -> str:
    text = _normalize_text_artifacts(text)
    escaped: list[str] = []

    for char in text:
        if char == "\\":
            escaped.append("\\textbackslash{}")
        elif char == "{":
            escaped.append("\\{")
        elif char == "}":
            escaped.append("\\}")
        elif char == "#":
            escaped.append("\\#")
        elif char == "$":
            escaped.append("\\$")
        elif char == "%":
            escaped.append("\\%")
        elif char == "&":
            escaped.append("\\&")
        elif char == "_":
            escaped.append("\\_")
        elif char == "^":
            escaped.append("\\textasciicircum{}")
        elif char == "~":
            escaped.append("\\textasciitilde{}")
        elif ord(char) > 127:
            # Non-ASCII character not handled above: replace with a safe ASCII
            # placeholder rather than letting pdflatex crash with a Unicode error.
            # (Box-drawing chars, arrows, etc. should be caught by
            # _normalize_text_artifacts first; this is a last-resort safety net.)
            escaped.append("?")
        else:
            escaped.append(char)

    return "".join(escaped)


def _render_comment(key: str, value: str) -> str:
    safe_value = " ".join(_normalize_text_artifacts(value).split()).strip()
    return f"% {key}: {safe_value}"


def _normalize_text_artifacts(text: str) -> str:
    normalized = unicodedata.normalize("NFKC", text)

    for source, replacement in COMMON_TEXT_REPLACEMENTS.items():
        normalized = normalized.replace(source, replacement)

    return normalized


def _strip_private_source_blocks(text: str) -> str:
    """Remove reader-facing private upload URLs and empty Further Reading blocks."""
    blocks = re.split(r"\n\s*\n", text)
    cleaned_blocks: list[str] = []
    index = 0

    while index < len(blocks):
        block = blocks[index].strip()
        if not block:
            index += 1
            continue

        heading = _strip_heading_markup(block.splitlines()[0]).strip(":").lower()
        if heading == "further reading":
            collected = [block]
            next_index = index + 1
            while next_index < len(blocks):
                next_block = blocks[next_index].strip()
                if not next_block:
                    next_index += 1
                    continue
                next_heading = _extract_standalone_heading([next_block.splitlines()[0].strip()])
                if next_heading and next_heading.lower().strip(":") != "further reading":
                    break
                if _is_bullet_list(next_block.splitlines()) or PRIVATE_SOURCE_URL_PATTERN.search(next_block):
                    collected.append(next_block)
                    next_index += 1
                    continue
                break

            if PRIVATE_SOURCE_URL_PATTERN.search("\n\n".join(collected)):
                index = next_index
                continue

        cleaned_lines = [
            line
            for line in block.splitlines()
            if not PRIVATE_SOURCE_URL_PATTERN.search(line)
        ]
        cleaned_block = "\n".join(cleaned_lines).strip()
        if cleaned_block and _strip_heading_markup(cleaned_block).strip(":").lower() != "further reading":
            cleaned_blocks.append(cleaned_block)
        index += 1

    return "\n\n".join(cleaned_blocks)
